xl : 200 # 水路長(m)
nx: 51  # x方向格子数
j_channel: 1 # 水路の状態　1=一定勾配 2=勾配変化点あり
# j_channel=1の場合
slope: 0.002 # 全体の勾配
# j_channel=2の場合
x_slope : 100 # 勾配変化点
slope1 : 0.001 # 上流側勾配
slope2 : 0.01 # 下流側勾配
xb1 : 90 # 突起始り地点の上流端からの距離（m)
xb2 : 100 # 突起頂点の上流端からの距離(m)
xb3 : 110 # 突起終了地点の上流からの距離(m)
dbed : 0. #突起高さ(m)
xw1 : 80 # 川幅変化点1の位置(m)
xw2 : 100 # 川幅変化点2の位置(m)
xw3 : 120 # 川幅変化点3の位置(m)
w0: 1 # 川幅1(m)(上流端)
w1: 1 # 川幅2(m)
w2: 0.75 # 川幅3(m)
w3: 1 # 川幅4(m)
w4: 1 # 川幅5(m)(下流端)
qp : 1 #単位幅流量(m**2/2)
g : 9.8 #重力加速度
snm : 0.025 # 粗度係数
alh : 0.6 # 水位計算緩和係数
lmax : 50 # 水位計算最大繰り返し回数
errmax : 0.0001 # 打ち切り誤差
hmin : 0.01 # 最小水深(m)
j_upstm : 2 # 上流端の条件 1=Wall, 2=Free, 3=Fixed Value
j_dwstm : 3 # 下流端の条件
alpha_up: 1.0 # 上流端の水深(等流水深に対する割合)
alpha_dw: 0.7 # 下流端の水深(等流水深に対する割合)

etime : 400 # 計算終了時間(sec)
dt : 0.05 # 計算タイムステップ
tuk : 10 # アウトプットインターバル
